Bugfix/ab#23188 fix chefs event service
bcgov/common-hosted-form-service pull request #1295
Opened 2024-02-23 17:59 UTC by jimmyPasta

# Description
createSubmission is called in 3 scenarios
- on saving of draft submissions - click the save icon on a brand new submission
- on submit of a brand new draft submission
- on submit of a submission that is not a draft

It does not get called when updating a draft submission

This problem solves events not being fired on the update of submissions when submit is clicked.
This problem simplifies the code for event subscription into a eventService

## Types of changes
Bug fix (non-breaking change which fixes an issue) 

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have checked that unit tests pass locally with my changes
- [x] I have run the npm script lint on the frontend and backend
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] I have approval from the product owner for the contribution in this pull request

## Further comments
Will walk through the code changes

2024-03-01 22:28 UTC, Stephan-McColm commented
Also tested via:
![image](https://github.com/bcgov/common-hosted-form-service/assets/143556068/8e58676e-3c75-4a93-adcc-41dfd967d9c9)

2024-03-05 00:00 UTC, usingtechnology requested changes
Question about DRAFT publish events... may have missed something but appears that is no longer sent.

2024-03-05 00:00 UTC, usingtechnology commented on app/src/forms/form/service.js
> +      eventService.publishFormEvent(formId, version.id, version.published);
I don't see how this is sending the `FORM_DRAFT_PUBLISHED` event? `eventService.publishFormEvent` only sends the `FORM_PUBLISHED` and `FORM_UNPUBLISHED` events.

2024-03-05 17:02 UTC, usingtechnology approved these changes
we can deal with a tiny clean up of unused events in another PR.

2024-03-05 17:08 UTC, vijaivir approved these changes

2024-03-06 00:07 UTC, WalterMoar approved these changes

2024-03-06 00:07 UTC, merged