Add encoded JWT token to CHEFS context
bcgov/common-hosted-form-service pull request #1326
Opened 2024-04-24 17:01 UTC by bcvesalink

# Description

This PR is to add the encoded JWT token to CHEFS context to use it in `Calculated values` same way as `token` (decoded JWT token) and `user`. That would mean we can use it to call CHEFS API securely by using full `encoded JWT token` in a header instead unrestricted `API key`. Also, this would help identify the user who calling the API, which is required by RLS (Row level Security)

## Types of changes

New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have checked that unit tests pass locally with my changes
- [x] I have run the npm script lint on the frontend and backend
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] I have approval from the product owner for the contribution in this pull request

## Further comments

2024-04-24 19:32 UTC, usingtechnology submitted a review, later dismissed
Looks good.

2024-04-24 20:00 UTC, WalterMoar requested changes
Wouldn't this allow a form to impersonate the user for *any* forms that the user owns? What about problems with the token being valid for the standard realm?

2024-04-25 15:21 UTC, WalterMoar commented
I created a proof of concept form that, when displayed, will delete all the user's forms.
- Log into https://chefs-dev.apps.silver.devops.gov.bc.ca/pr-1326
- Create a form
- Visit https://chefs-dev.apps.silver.devops.gov.bc.ca/pr-1326/form/submit?f=c6a7fc79-d70b-4aa0-b589-22b6b21a037f

2024-04-25 18:15 UTC, bcvesalink commented
yes, there is a security issue making encoded token available for form designers, so closing this PR

2024-04-25 18:15 UTC, closed without merging