Schema Response Change
bcgov/common-hosted-form-service pull request #207
Opened 2021-07-07 02:57 UTC by MichaelChung123

# Description
Removing formSchema from the fetchDrafts response

## Types of changes
1. Made changes to introduce a Boolean schema parameter that includes or removes the formSchema response
2. Added documentation changes
3. Added test changes

## Checklist

- [X] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [X] I have checked that unit tests pass locally with my changes
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

2021-07-07 03:04 UTC, bcgov-nr-csst commented
PR Deployed at: https://chefs-dev.apps.silver.devops.gov.bc.ca/pr-207

2021-07-07 17:27 UTC, TimCsaky approved these changes
looks good

2021-07-07 23:38 UTC, loneil requested changes

2021-07-07 23:38 UTC, loneil commented on app/frontend/src/services/formService.js
> +   * @param {boolean} [schema=undefined] Require schema in the response
Not needed

2021-07-07 23:38 UTC, loneil commented on app/src/docs/v1.api-spec.yaml
> +
Extra comment?

2021-07-07 23:38 UTC, loneil commented on app/frontend/tests/unit/store/modules/form.actions.spec.js
> +      ]));
Don't think the test needs to know about `schema` (probably no FE changes needed now)

2021-07-07 23:38 UTC, loneil commented on app/frontend/src/components/forms/manage/CurrentDraft.vue
>  </template>
We can delete this file

2021-07-07 23:46 UTC, MichaelChung123 commented
Rebased

2021-07-07 23:53 UTC, bcgov-nr-csst commented
PR Deployed at: https://chefs-dev.apps.silver.devops.gov.bc.ca/pr-207

2021-07-08 00:02 UTC, loneil approved these changes
Looks great, tested out end-to-end form creation and versioning/publishing etc and things are working good.

2021-07-08 16:15 UTC, TimCsaky approved these changes

2021-07-08 17:25 UTC, jujaga approved these changes

2021-07-08 17:25 UTC, merged