Fixing Update button
bcgov/common-hosted-form-service pull request #263
Opened 2021-12-02 19:16 UTC by MichaelChung123

# Description
Changing the Update button based off of the status selected. Update button is disabled when nothing is selected.

REF: https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2296

## Types of changes
Making conditional changes to the Update button in the StatusPanel component.

## Checklist

- [X] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [X] I have checked that unit tests pass locally with my changes
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

## Further comments

2021-12-02 19:24 UTC, bcgov-nr-csst commented
PR Deployed at: https://chefs-dev.apps.silver.devops.gov.bc.ca/pr-263

2021-12-02 19:27 UTC, jujaga approved these changes

2021-12-02 19:38 UTC, loneil approved these changes

2021-12-02 21:06 UTC, TimCsaky approved these changes

2021-12-03 00:54 UTC, loneil commented
Marking as draft for now, UX person going to take a look

2021-12-15 00:59 UTC, jujaga requested changes
Something went wrong on rebase - the button no longer shows text.

2021-12-15 22:39 UTC, jujaga approved these changes

2021-12-15 23:09 UTC, loneil approved these changes

2021-12-16 17:20 UTC, merged